use_frameworks!

platform :ios, '8.0'

target 'ASBaseTool_Example' do
  pod 'ASBaseTool', :path => '../'

  target 'ASBaseTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
